#!/bin/sh

# Run golangci-lint on staged files
echo "Running golangci-lint..."
golangci-lint run --fix

# Check if the linter passed
if [ $? -ne 0 ]; then
  echo "❌ golangci-lint found issues. Commit aborted."
  exit 1
fi