DROP USER IF EXISTS 'mysql'@'%';
CREATE USER 'mysql'@'%' IDENTIFIED BY 'secret1234';
GRANT REPLICATION CLIENT ON *.* TO 'mysql'@'%';
GRANT REPLICATION SLAVE ON *.* TO 'mysql'@'%';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'%';
FLUSH PRIVILEGES;